# Generated by Django 6.0.3 on 2026-03-28 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfanityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('chat', 'Chat Message'), ('project', 'Project Description'), ('bid', 'Bid Message'), ('other', 'Other')], default='chat', max_length=20)),
                ('content_snippet', models.CharField(help_text='The message/text that triggered the report', max_length=500)),
                ('detected_words', models.JSONField(default=list, help_text='List of profanity words found')),
                ('context_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object (chat room, project, bid)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('warned', 'User Warned'), ('banned', 'User Banned'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profanity_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profanity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
