# Generated by Django 6.0.3 on 2026-03-27 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(500)])),
                ('proposal', models.TextField(max_length=5000)),
                ('proposal_type', models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'AI Generated')], default='manual', max_length=15)),
                ('portfolio_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('ignored', 'Ignored'), ('accepted', 'Accepted')], default='pending', max_length=15)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Position/rank among all bids on this project')),
                ('delivery_days', models.PositiveIntegerField(default=7, help_text='Estimated delivery time in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.project')),
            ],
            options={
                'ordering': ['rank', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='bids_bid_status_071bbe_idx'), models.Index(fields=['freelancer', 'created_at'], name='bids_bid_freelan_3d799c_idx')],
                'unique_together': {('freelancer', 'project')},
            },
        ),
    ]
