# Generated by Django 6.0.3 on 2026-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attached_file',
            field=models.FileField(blank=True, help_text='Optional PDF or document detailing project requirements', null=True, upload_to='project_files/'),
        ),
    ]
